### ISSUE TITLE
Long error message

### ISSUE THREAD

**Issue by jin-park** [jakewilliami/SpelledOut.jl#25]
I feel like this error message is too long.
<img width="1437" alt="Screen Shot 2021-01-13 at 2 50 33 PM" src="https://user-images.githubusercontent.com/61643387/104412066-ef285380-55ae-11eb-80e5-24f014cdb24d.png">
How about something like `ERROR: SpelledOut.jl does not support numbers larger than 10^120 - 1.  Sorry about that!`?

**Comment by jin-park** [comment]
btw, nice package! I might be able to add support for Korean if I have time :)

**Comment by jakewilliami** [comment]
@jin-park lol, maybe you are right :P  Should be fixed as of 14afec0!  Thanks for pointing that out—I think I was being silly when I wrote it...

Regarding Korean, please do!!  I welcome supporters!  I have a `universal` branch (which is currently up-to-date with the master branch) and has the infrastructure to add more languages (you will see how; there is simply a `lang` kwarg in the main function) :)

All good if I close this issue?

**Comment by jin-park** [comment]
yep
