### ISSUE TITLE
Bigger float don't work

### ISSUE THREAD

**Issue by jin-park** [jakewilliami/SpelledOut.jl#37]
Hi :) The decimal version of spelled_out doesn't seem to work for floats bigger than 1,000,000. Maybe it's because of that "1e6" notation?

<img width="1440" alt="Screen Shot 2021-01-27 at 5 36 39 PM" src="https://user-images.githubusercontent.com/61643387/105965368-aa301100-60c6-11eb-8bb7-3faf79a364b4.png">

**Comment by jakewilliami** [comment]
Hi there!  I tried fixing that in #32.  Can you verify that you are using the most recent version of `SpelledOut`? :)

**Comment by jin-park** [comment]
Ah, so for some reason I cannot update the package. When I do `add SpelledOut#master` this error message pops up. Do you know how to fix this? :)

<img width="1440" alt="Screen Shot 2021-01-27 at 5 46 47 PM" src="https://user-images.githubusercontent.com/61643387/105966149-a2bd3780-60c7-11eb-8cae-9b4401250f16.png">

**Comment by jakewilliami** [comment]
That said, what I recall of that fix felt a bit hacky.  If you can think of another way to go about this, I'd be happy for you to contribute!

Strange about that error message.  I've had some trouble in the past with the registry in general.  Could you try `add SpelledOut@1.1.0`?

**Comment by jin-park** [comment]
hmmm no luck :( Maybe it's a problem on my end? I guess I'll have to google this

<img width="1440" alt="Screen Shot 2021-01-27 at 5 51 23 PM" src="https://user-images.githubusercontent.com/61643387/105966651-473f7980-60c8-11eb-9037-11fa70051651.png">

**Comment by jakewilliami** [comment]
Hmm, that's very strange.  Please google that issue.  It might be worth [deleting the general registry and updating](https://discourse.julialang.org/t/registry-dirty/17989/2).  Either way, I believe this is still an issue needing fixed, so I will work on fixing this issue now (I will reopen #32)

**Comment by jin-park** [comment]
Ah I see, I'll have to try that. Well, thanks for the help :)

**Comment by jakewilliami** [comment]
Let me know how you get on :)  I'll update you here when I fix this issue.  Thank you for bringing this to my attention, as I now realise this must be a slightly different issue to #32 (though a similar error)

**Comment by jakewilliami** [comment]
@jin-park It should be fixed now.  Let me know if you are happy for me to close the issue.  (See also #42)

**Comment by jakewilliami** [comment]
I am going to close this now because I'd like to push a new version (1.1.1).  We can always reopen this if you are still having problems :)
